name: legal_scan_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  lucide_icons: ^0.257.0
  http: ^1.3.0
  flutter_html: ^3.0.0
  flutter_markdown: ^0.7.1
  smooth_page_indicator: ^1.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.6
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
